In [2]:
import numpy as nu


In [4]:
nu.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
nu.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
nu.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
nu.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
nu.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
nu.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
nu.random.rand(25)

array([0.54703858, 0.38482022, 0.55140068, 0.99316875, 0.39995162,
       0.09749892, 0.18107008, 0.44580788, 0.2948242 , 0.5794132 ,
       0.94180947, 0.91800219, 0.9864238 , 0.89495576, 0.8464162 ,
       0.96573293, 0.10628197, 0.28024272, 0.87394991, 0.21055022,
       0.66922835, 0.06495419, 0.63905151, 0.81143133, 0.95312077])

In [13]:
nu.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
nu.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [2]:
nu.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
mat=nu.arange(1,26).reshape(5,5)

In [20]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [21]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[3:4,4:5]

array([[20]])

In [26]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [27]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [28]:
mat[3:6]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
nu.std(mat)

7.211102550927978

In [31]:
nu.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [32]:
nu.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [39]:
oned=nu.arange(0,12)
oned.dtype              

dtype('int32')

In [38]:
twod=nu.arange(0,12).reshape(3,4)
twod.ndim

2

In [41]:
threed=nu.arange(0,12).reshape(3,2,2) 
threed.shape

(3, 2, 2)

In [42]:
nu.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
nu.empty(3)

array([0., 0., 0.])

In [57]:
nu.ones(15).reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
maths=nu.random.randint(0,100,20)
maths                    

array([ 7, 72, 32, 40, 56, 80, 38,  5,  2, 51, 99, 42, 54, 85, 69, 23, 82,
       34, 44, 84])

In [9]:
nu.sort(maths)

array([ 2,  5,  7, 23, 32, 34, 38, 40, 42, 44, 51, 54, 56, 69, 72, 80, 82,
       84, 85, 99])

In [13]:
nu.flip(maths)

array([84, 44, 34, 82, 23, 69, 85, 54, 42, 99, 51,  2,  5, 38, 80, 56, 40,
       32, 72,  7])

In [15]:
nu.copy(maths)

array([ 7, 72, 32, 40, 56, 80, 38,  5,  2, 51, 99, 42, 54, 85, 69, 23, 82,
       34, 44, 84])

In [19]:
nu.eye(5,5).reshape(25,)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [20]:
nu.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
nu.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])